#include "/include/HelperCommands.inc"
#include "/include/New.inc"
#include "/include/Enum.inc"
#include "/include/Define.inc"

#define MAX_FURNITURE 100000
#define NRQUEST 50
#define NR_BRAZI 100
#define	DIALOG_UPDATES 830
#define GasMax 100
#define RunOutTime 20000
#define RefuelWait 5000
#define CAR_AMOUNT 700
#define MAX_ARM 500 // Limit
#define MAX_ROADBLOCKS 150
#define OwnedVeh(%0) 		caridxx[%0]

